shared:
  image: tianon/true
  volumes:
    - /tmp
graph:
  build: ./
  dockerfile: dockerfiles/graph.dockerfile
  links:
    - rethinkdb
  volumes_from:
    - shared
  volumes:
    - ./src:/usr/src/app/src
    - ./package.json:/usr/src/app/package.json
  environment:
    - RETHINK_HOST=rethinkdb
    - APP_PORT=3001
  expose:
    - 3001
webpack:
  build: ./
  dockerfile: dockerfiles/webpack.dockerfile
  ports:
    - 3000:3000
  links:
    - graph
  volumes_from:
    - shared
  volumes:
    - ./webpack:/usr/src/app/webpack
    - ./package.json:/usr/src/app/package.json
  environment:
    - WEBPACK_PORT=3000
    - APP_PORT=3001
    - APP_HOST=graph
rethinkdb:
  image: rethinkdb:2.1.1
  expose:
    - 28015
  ports:
    - 8080:8080
    - 28015:28015
db:
  image: mdillon/postgis
  ports:
    - 5432:5432
